services:
  neon:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    container_name: neon-proxy
    environment:
      - PG_CONNECTION_STRING=postgres://postgres:postgres@host.docker.internal:5432/canva_clone
    ports:
      - 4444:4444
